### ISSUE TITLE
sdk无法读取jar包中的配置

### ISSUE THREAD

**Issue by a19870822cp** [FISCO-BCOS/java-sdk#233]
1、当toml文件在jar包中的resource目录中时
`String configFile = Objects.requireNonNull(FiscoSdkConfig.class.getClassLoader().getResource(fileName)).getPath();
BcosSDK.build(configFile)`
无法成功读取配置文件构造BcosSDK
2、当.p12私钥文件在jar包中的resource目录中时
`KeyTool keyToolCommitteeMember = new P12KeyStore(path, PASSWORD);`
P12KeyStore也无法读取到配置文件

KeyTool.java中
`/** load information from the keyStoreFile */
    protected void load() {
        try {
            InputStream keyStoreFileInputStream = new FileInputStream(keyStoreFile);
            this.load(keyStoreFileInputStream);
        } catch (FileNotFoundException | org.bouncycastle.util.encoders.DecoderException e) {
            String errorMessage =
                    "load keys from "
                            + keyStoreFile
                            + " failed for FileNotFoundException, error message:"
                            + e.getMessage();
            logger.error(errorMessage);
            throw new LoadKeyStoreException(errorMessage, e);
        }
    }`
new FileInputStream(keyStoreFile)应该读取不到jar包中的配置

**Comment by dalaocu** [comment]
打入jar包中的文件，无法通过file的方式读取到。

对于类似的需求，可以尝试修改载入的配置，例如修改certPath的路径，然后将证书等文件放置到该路径下，以下是简单的参考使用示例：
```
public BcosSDK getSDK() throws ConfigException {
        ConfigProperty configProperty = new ConfigProperty();
         ......
         setCertPath(configProperty);
        ConfigOption option = new ConfigOption(configProperty);
        return new BcosSDK(option);
    }
    
    public void setCertPath(ConfigProperty configProperty) {
        Map<String, Object> cryptoMaterial = Maps.newHashMapWithExpectedSize(1);
        cryptoMaterial.put("certPath", "config");
        configProperty.setCryptoMaterial(cryptoMaterial);
    }
```

在gradle打包的时候，可以将配置文件联动打包到该目录下，参考：
```
jar {
    enabled = true
    destinationDir file('dist')
    archiveName project.name + version + '.jar'
    .......
    doLast {
        copy {
            from file('src/main/resources/')
            into 'dist/config'
        }
    }
}
```

**Comment by LuffySmile** [comment]
> 打入jar包中的文件，无法通过file的方式读取到。
> 
> 对于类似的需求，可以尝试修改载入的配置，例如修改certPath的路径，然后将证书等文件放置到该路径下，以下是简单的参考使用示例：
> 
> ```
> public BcosSDK getSDK() throws ConfigException {
>         ConfigProperty configProperty = new ConfigProperty();
>          ......
>          setCertPath(configProperty);
>         ConfigOption option = new ConfigOption(configProperty);
>         return new BcosSDK(option);
>     }
>     
>     public void setCertPath(ConfigProperty configProperty) {
>         Map<String, Object> cryptoMaterial = Maps.newHashMapWithExpectedSize(1);
>         cryptoMaterial.put("certPath", "config");
>         configProperty.setCryptoMaterial(cryptoMaterial);
>     }
> ```
> 
> 在gradle打包的时候，可以将配置文件联动打包到该目录下，参考：
> 
> ```
> jar {
>     enabled = true
>     destinationDir file('dist')
>     archiveName project.name + version + '.jar'
>     .......
>     doLast {
>         copy {
>             from file('src/main/resources/')
>             into 'dist/config'
>         }
>     }
> }
> ```

请问这个省略号里应该填写什么
![image](https://user-images.githubusercontent.com/34114979/106345642-a978c400-62ec-11eb-8516-7759e0dbb75c.png)
