### ISSUE TITLE
你好，本地eclipse搭建asset-app 提示证书报错，具体问题描述如下

### ISSUE THREAD

**Issue by freezehe** [FISCO-BCOS/java-sdk#242]
我所下载的fisco-bcos 是最新版2.7的版本

问题描述：
1.参考https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/sdk_application.html 网站能在我云服务器运行成功，截图如下：
![image](https://user-images.githubusercontent.com/11324122/103993185-2d4cfe00-51d0-11eb-96e4-ca3780409591.png)
2.然后我本地eclipse搭建maven 工程，拷贝相同的证书到eclispe目录下面，层级结构和配置如下：
![image](https://user-images.githubusercontent.com/11324122/103993273-51104400-51d0-11eb-952d-c9815c80b5a8.png)
applicationContext.xml 仅修改一处配置。
![image](https://user-images.githubusercontent.com/11324122/103993305-5cfc0600-51d0-11eb-9bf0-cc48374bfcf5.png)
3.eclipse运行报错：
![image](https://user-images.githubusercontent.com/11324122/103993442-903e9500-51d0-11eb-8767-564839ebb8ef.png)

不知道什么问题，困扰了我几天了，麻烦解答一下，你们官方微信群我也发了问题描述，可是没有人回复，希望fisco-bcos社区后期能够为我们这些爱好者提供一下技术支持，谢谢！

**Comment by freezehe** [comment]
再补充第四点，linux 服务器上是运行脚本【bash asset_run.sh deploy】这样运行的，我本地eclipse 是这样运行的，
![Uploading image.png…]()，是不是参数有问题？

**Comment by freezehe** [comment]
![Uploading image.png…]()

**Comment by cyjseagull** [comment]
java sdk 2.7.1才支持从resource路径加载证书和私钥文件，升级java sdk到`2.7.1`版本即可：

gradlew的引入方式：

```
compile ('org.fisco-bcos.java-sdk:fisco-bcos-java-sdk:2.7.1')
```

maven的引入方式：

```xml
<dependency>
    <groupId>org.fisco-bcos.java-sdk</groupId>
    <artifactId>fisco-bcos-java-sdk</artifactId>
    <version>2.7.1</version>
</dependency>
```
