### ISSUE TITLE
合约事件推送,fromblock条件不起作用

### ISSUE THREAD

**Issue by longJJ2016** [FISCO-BCOS/java-sdk#247]
![image](https://user-images.githubusercontent.com/22811031/104669447-f9646200-5714-11eb-8c04-c5000133cd72.png)
![image](https://user-images.githubusercontent.com/22811031/104669370-db96fd00-5714-11eb-8726-ee83e24ab58c.png)
如图，总块高为12084，设置fromblock为latest，仍然推送小于总块高的数据
设置为具体块高 10000、12000等整数都是无效，仍然从最低11412块高开始推送
PS：(等接收到11412数据时，都会等几分，猜测从0-11412检索花了不少时间)

**Comment by starzhou** [comment]
duplicate question #253
