### ISSUE TITLE
javasdk建链时 不成功的问题 

### ISSUE THREAD

**Issue by chen821493467** [FISCO-BCOS/java-sdk#251]
证书什么的完全没有问题， 我copy了很多次，最终需要安装java依赖   sudo yum install -y java java-devel  ， 服务器版本是 centos7.6

**Comment by chen821493467** [comment]
报错日志：
![image](https://user-images.githubusercontent.com/34762948/104883146-43607880-599f-11eb-8d87-7abacfdc4abc.png)

**Comment by chen821493467** [comment]
报错日志 ：  Input stream does not contain valid certificates.  主要就是显示这个

**Comment by cyjseagull** [comment]
centos系统不仅需要安装java，还需要安装java依赖，可通过如下命令解决：

```bash
# ubuntu系统安装java
sudo apt install -y default-jdk

#centos系统安装java
sudo yum install -y java java-devel
```

文档请参考[准备java依赖](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html#id9)

--------- 

2.7.2版本，关于java sdk握手失败，我们会增加检查，并输出详细的版本信息，进而降低问题定位路径，具体可以关注 #252
