### ISSUE TITLE
设置EventLogParams的FromBlock不生效

### ISSUE THREAD

**Issue by starzhou** [FISCO-BCOS/java-sdk#253]
bug是： 设置 EventLogParams 设置fromBlock 不管改成什么值都从最初块开始

   private EventLogParams generateNewParams() {
        EventLogParams params = new EventLogParams();
        params.setToBlock(getParams().getToBlock());
        params.setAddresses(getParams().getAddresses());
        params.setTopics(getParams().getTopics());
        if (lastBlockNumber == null) {
            params.setFromBlock(params.getFromBlock());
        } else {
            params.setFromBlock(lastBlockNumber.toString());
        }
        return params;
    }

当进入lastBlockNumber == null的代码后  setFromBlock  应该是params.setFromBlock(getParams().getFromBlock());

**Comment by cyjseagull** [comment]
Fixed in [#254](https://github.com/FISCO-BCOS/java-sdk/pull/254)
