### ISSUE TITLE
JAVA SDK 与spring-boot-starter-parent 版本2.0.5.RELEASE结合,报Please check the certificate and ensure that the SDK and the node are in the same agency agency错误,使用版本spring-boot-starter-parent-1.5.9.RELEASE版本正常 ,JAVA版本1.8 

### ISSUE THREAD

**Issue by heynooo** [FISCO-BCOS/java-sdk#261]
JAVA SDK 与spring-boot-starter-parent 版本2.0.5.RELEASE结合,报Please check the certificate and ensure that the SDK and the node are in the same agency agency错误,使用版本spring-boot-starter-parent-1.5.9.RELEASE版本正常 ,JAVA版本1.8

**Comment by cyjseagull** [comment]
握手失败的报错：

```
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
```

**Comment by cyjseagull** [comment]
**问题原因**

- [spring-boot-starter-parent 2.0.5](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/2.0.5.RELEASE) 依赖了`4.1.29.Final`的netty；

- [spring-boot-starter-parent 1.5.9](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/1.5.9.RELEASE) 不依赖netty

- [fisco-bcos-java-sdk](https://mvnrepository.com/artifact/org.fisco-bcos.java-sdk/fisco-bcos-java-sdk/2.7.1) 依赖`4.1.53.Final`版本netty

当`fisco-bcos-java-sdk`和`spring-boot-starter-parent 1.5.9`一起使用时，没有使用不同版本的`netty`，不会产生jar包冲突；
当`fisco-bcos-java-sdk`和`spring-boot-starter-parent 2.0.5`一起使用时，前者使用了高版本`netty`，后者使用低版本
`netty`，通过`maven helper`工具调试发现，最终选取了低版本的`netty 4.1.29.Final`的netty，导致`java sdk`与节点建连失败。

**解决方法**

- 升级到最新的`2.4.2`版本的`spring-boot-starter-parent`，最新版本的`spring-boot-starter-parent`依赖的是`4.1.58.Final`版本的netty，可以正常使用。

**Comment by heynooo** [comment]
好的 谢谢 解决了 

```
	    <dependency>
            <groupId>org.fisco-bcos.java-sdk</groupId>
            <artifactId>java-sdk</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
            <version>2.6.1-rc1</version>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.50.Final</version>
            <scope>compile</scope>
        </dependency>
```
