### ISSUE TITLE
Java SDK在window下使用IDEA，把账户公钥放在account\ecdsa下，出现target\\classes\\account\\ecdsa (拒绝访问。)问题

### ISSUE THREAD

**Issue by LuffySmile** [FISCO-BCOS/java-sdk#262]

**Comment by cyjseagull** [comment]
Windows下，`URL.getPath`返回的路径出现字符转义，导致路径错误，已经在dev分支修复，并上传了`fisco-bcos-java-sdk-2.7.2-SNAPSHOT`

参考 #260 ，使用`2.7.2-snapshot`版本试试：

```
compile ('org.fisco-bcos.java-sdk:fisco-bcos-java-sdk:2.7.2-SNAPSHOT")
```

maven请使用：

```xml
<dependency>
    <groupId>org.fisco-bcos.java-sdk</groupId>
    <artifactId>fisco-bcos-java-sdk</artifactId>
    <version>2.7.2-SNAPSHOT</version>
</dependency>
```

**Comment by cyjseagull** [comment]
> _No description provided._

希望可以提供更明确的报错提示~

目前Windows下，`URL.getPath`返回的路径出现字符转义，导致路径错误，已经在dev分支修复，并上传了`fisco-bcos-java-sdk-2.7.2-SNAPSHOT`

参考 #260 ，使用`2.7.2-snapshot`版本试试：

```
compile ('org.fisco-bcos.java-sdk:fisco-bcos-java-sdk:2.7.2-SNAPSHOT")
```

maven请使用：

```xml
<dependency>
    <groupId>org.fisco-bcos.java-sdk</groupId>
    <artifactId>fisco-bcos-java-sdk</artifactId>
    <version>2.7.2-SNAPSHOT</version>
</dependency>
```

**Comment by LuffySmile** [comment]
> > _No description provided._
> 
> 希望可以提供更明确的报错提示~
> 
> 1. 确认拒绝访问的路径是否存在
> 2. 确认本账户是否有对该路径的访问权限

路径是存在的，权限应该是有的，因为可以把生成的账户信息保存到这个路径下。我是通过控制台生成账户信息，然后把账户信息保存到src/main/resources/account/ecdsa，在config.toml中也配置相关的内容。我是在window环境下使用IDEA开发的。

**Comment by LuffySmile** [comment]
> _No description provided._

已经解决了，是配置文件的问题。配置account.accountFilePath时要具体到账户的公钥文件
