### ISSUE TITLE
能否给个验证交易proof的demo

### ISSUE THREAD

**Issue by leehus** [FISCO-BCOS/java-sdk#267]
获取交易的proof后：
TransactionWithProof transactionByHashWithProof = client.getTransactionByHashWithProof(hash);
然后根据说明文档：
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/design/merkle_proof.html
做验证，总是无法得到一致的hash。
之后我用上述说明文档中的数据做验证也没成功，hash算法我用的是sdk中的Keccak256，SM3Hash都试过；
能否给个在例子中给一个验证的demo，或者用说明文档中的数据写几行伪代码供参考，谢谢。

**Comment by cyjseagull** [comment]
请参考[web3sdk的proof验证类MerkleProofUtility](https://github.com/FISCO-BCOS/web3sdk/blob/master/src/main/java/org/fisco/bcos/web3j/tx/MerkleProofUtility.java)

**Comment by leehus** [comment]
验证成功，谢谢。
