### ISSUE TITLE
java sdk 可以将获取交易hash 和交易回执等方法开放处理

### ISSUE THREAD

**Issue by linbin524** [FISCO-BCOS/java-sdk#283]
目标：java sdk 可以适当的像rpc 开放接口，提供拆封组合。

现有情况：sol 2 java 代码里面是基本都是封闭业务调用操作，java sdk 里面 又没有直接可以拿到交易signData,导致应用层必须面临一种抉择，要么直接使用sol 2java 代码获取回执（并发情况下，不友好，见下文），要么就要舍弃sol 2java 代码全部自主拼接

问题和解法：其实只要在sol2java 新增一个获取交易hash的就可以了，生产环境中 出现 并发请求 receipt （因为交易和获取回执都在一个方法里面） 导致某些交易由于还没同步区块，超时，应用层以为交易失败，但其实底层在后面有将超时的数据insert 区块链的table 合约db，所以就变得很怪，如果超时阶段先返回 交易hash，后续用队列或者其他服务来进行取回，可以满足生产。

**Comment by cyjseagull** [comment]
> 步区块，超时，应用层以为交易失败，但其实底层在后面有将超时的数据insert 区块链的table 合约db，所以就变得很怪，如果超时阶段先返回 交易hash，后续用队列或者其他服务来进行取回，可以满足生产。

发送交易的时，返回交易哈希的接口预计下个版本添加，目前可利用`getSignedTransactionForxxx`的方法解决。


Java SDK生成的java代码中，为每个接口提供了`getSignedTransactionForxxx`的方法，可以调用该方法，获取`SignedTranaction`之后计算哈希，以HelloWorld为例：

```java
HelloWorld hello = HelloWorld.deploy(client, cryptoKeypair);
// 获取部署合约的交易回执
TransactionReceipt deployReceipt = hello.getDeployReceipt();
// 通过回执获取交易哈希
String hash = deployReceipt.getTransactionHash();

// 调用set方法发送交易
String signedTransactionForSet = hello.getSignedTransactionForSet("test");

// 使用AssembleTransactionProcessor的sendTransactionAsync发送signedTransactionForSet

```

**Comment by cyjseagull** [comment]
> 目标：java sdk 可以适当的像rpc 开放接口，提供拆封组合。
> 
> 现有情况：sol 2 java 代码里面是基本都是封闭业务调用操作，java sdk 里面 又没有直接可以拿到交易signData,导致应用层必须面临一种抉择，要么直接使用sol 2java 代码获取回执（并发情况下，不友好，见下文），要么就要舍弃sol 2java 代码全部自主拼接
> 
> 问题和解法：其实只要在sol2java 新增一个获取交易hash的就可以了，生产环境中 出现 并发请求 receipt （因为交易和获取回执都在一个方法里面） 导致某些交易由于还没同步区块，超时，应用层以为交易失败，但其实底层在后面有将超时的数据insert 区块链的table 合约db，所以就变得很怪，如果超时阶段先返回 交易hash，后续用队列或者其他服务来进行取回，可以满足生产。




2.8.0生成的java接口时，返回交易哈希，可以满足您的需求。

**您可以直接拉取控制台的dev分支最新代码，并使用dev分支的sol2java.sh脚本将合约代码转换为java代码**

2.8.0-SNAPSHOT, 引入方式：
```
compile ('org.fisco-bcos.java-sdk:fisco-bcos-java-sdk:2.8.0-SNAPSHOT')
```

```
<dependency>
    <groupId>org.fisco-bcos.java-sdk</groupId>
    <artifactId>fisco-bcos-java-sdk</artifactId>
    <version>2.8.0-SNAPSHOT</version>
</dependency>
```
