### ISSUE TITLE
问题：请问如何确定Transaction的合约地址？

### ISSUE THREAD

**Issue by leehus** [FISCO-BCOS/java-sdk#297]
通过client.getBlockByNumber(blockNumber, true)后，得到的Transaction列表，
1,怎样能确定一笔Transaction是在那个合约上的？
能否在返回的对象中加入该属性，或者有其他的查询方法可以获取到？

**Comment by cyjseagull** [comment]
获取的transaction中的`getTo()`方法可以获取交易对应的合约地址。
