### ISSUE TITLE
java-sdk2.7.2 maven 引用io.netty4.1.66 这是个错误的引用

### ISSUE THREAD

**Issue by xyh393** [FISCO-BCOS/java-sdk#332]
gradle 环境，java-sdk2.7.2 引用的io.netty4.1.53 运行正常；
maven 环境，java-sdk2.7.2 引用的io.netty4.1.66 运行失败，原因：io.netty4.1.66缺失internal包；解决办法如下：

               <dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-all</artifactId>
			<version>4.1.53.Final</version>
		</dependency>

		<dependency>
			<groupId>org.fisco-bcos.java-sdk</groupId>
			<artifactId>fisco-bcos-java-sdk</artifactId>
			<version>2.7.2</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty-all</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

不能放截图，有点小遗憾！

**Comment by cyjseagull** [comment]
关于sdk连接节点失败的详细排查方法请参考 issue #536
