### ISSUE TITLE
netty upgrade

### ISSUE THREAD

**Issue by cyjseagull** [FISCO-BCOS/java-sdk#469]
java-sdk currently relies on netty 4.1.53, and many components such as spring-boot currently rely on netty versions higher than 4.1.53. When spring-boot is used in combination with java-sdk, many networks cannot be connected due to conflicting netty versions, are there any plans to upgrade netty to 4.1.72?

**Comment by PC-Chiu** [comment]
升级 netty 到 4.1.72，java SDK启动报错：privatekey type not supported pkcs#8，貌似 SDK 证书只能用 p12，但是目前的 Java SDK 没有提供配置 SDK 证书密码的功能。

**Comment by cyjseagull** [comment]
关于sdk连接节点失败的详细排查方法请参考 issue #536
