### ISSUE TITLE
Help wanted: solution for secp256k1 being disabled

### ISSUE THREAD

**Issue by cyjseagull** [FISCO-BCOS/java-sdk#470]
With the upgrade of the jdk version, the secp256k1 curve has been gradually disabled. Are there plans to use other curves to replace secp256k1?

**Comment by PC-Chiu** [comment]
If your JDK/JRE version later than 8u300.

1. Path to '{JRE_HOME}/jre/lib/security/';
2. Open 'java.security' with text editor;
3. Find the key word 'jdk.disabled.namedCurves =' and where you can find 'secp256k1';
4. Remove 'secp256k1' from the config value list.

If your JDK/JRE version earlier than 8u300, maybe not.

**Comment by PC-Chiu** [comment]
A simpler solution: Add JVM start options `-Djdk.tls.namedGroups="secp256k1"`

**Comment by PC-Chiu** [comment]
Or, add JVM start options: `-Djdk.tls.namedGroups="secp256k1`

**Comment by PC-Chiu** [comment]
Reference: [https://www.java.com/zh-CN/download/help/release_changes.html](https://www.java.com/zh-CN/download/help/release_changes.html)

**Comment by cyjseagull** [comment]
jdk release note can reference to https://www.oracle.com/java/technologies/javase/jdk-relnotes-index.html

**Comment by cyjseagull** [comment]
can reference to #536
