### ISSUE TITLE
ContractCode与FunctionEncoderInterface的部分方法定义不一致导致 无法解析Event失败

### ISSUE THREAD

**Issue by yanchain** [FISCO-BCOS/java-sdk#654]
https://github.com/FISCO-BCOS/java-sdk/blob/67bdc1e13194277fb3529bafa1cfa84e9c1f36fd/sdk-codec/src/main/java/org/fisco/bcos/sdk/v3/codec/wrapper/ContractABIDefinition.java#L110
这个地方有点问题哦，在ContractABIDefinition 中的addEvent方法添加到eventTopicToEvents中的key是截取取topic的0-4的的新数组，而且这个key还ByteBuffer.wrap了一下，而ContractCodec中，除了decodeEvent 其他的解析事件的方法都是以完整的topic解码后到eventTopicToEvents 拿ABIDefinition ，最终获取的都是null，其他方法都无法使用,如decodeEventByTopic，decodeEventByInterface，decodeEventToString，decodeEventByTopicToString，decodeEventByInterfaceToString，这些方法均无法使用

**Comment by kyonRay** [comment]
Hi @yanchain ,
这个bug在 #693 这个PR解决了，感谢指出 :)
