### ISSUE TITLE
 SpringBoot项目集成MQ连接Java-sdk时出错

### ISSUE THREAD

**Issue by MJJ128** [FISCO-BCOS/java-sdk#758]
SpringBoot项目集成MQ连接Java-sdk时出错：
* TRACE INFORMATION:
----------------------------
====> STEP1: try to connect nodes with ecdsa context...
<==== STEP1-1: Load certificates for ecdsa context success...
<==== STEP1 Result: try to connect nodes with ecdsa context failed. reason:
init failed SSL context init failed, please make sure your cert and key files are properly configured. error info: PrivateKey type not supported PKCS#8
----------------------------
====> STEP2: connect nodes with ecdsa context failed, try to connect nodes with sm-context...
<==== STEP2 Result: connect with sm context failed for cert missing.
* Missed certificates: 
[/E:/WorkSpace/GitHub/blockchain-eventListen-service/controller/target/classes/conf/dev\gm\gmca.crt,/E:/WorkSpace/GitHub/blockchain-eventListen-service/controller/target/classes/conf/dev\gm\gmsdk.crt,/E:/WorkSpace/GitHub/blockchain-eventListen-service/controller/target/classes/conf/dev\gm\gmsdk.key,/E:/WorkSpace/GitHub/blockchain-eventListen-service/controller/target/classes/conf/dev\gm\gmensdk.key,/E:/WorkSpace/GitHub/blockchain-eventListen-service/controller/target/classes/conf/dev\gm\gmensdk.crt,]
currentPath: E:\WorkSpace\GitHub\blockchain-eventListen-service
----------------------------
<====> Error: try to connect nodes with both ecdsa and sm context failed <====>
<====> Please refer to github issue: https://github.com/FISCO-BCOS/java-sdk/issues/536 
<====> Please refer to fisco-docs: https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/faq/connect.html 
----------------------------
* FISCO BCOS Java SDK Version: 2.9.1
* Support secp256k1 : true
* Java Version : 1.8.0_301
* JDK Disabled NamedCurves : null
* JDK DisableNative Option : false
* OS Name : Windows 10
* OS Arch : amd64
* OS Version : 10.0
* JVM Version : 25.301-b09
* JVM Vendor : Oracle Corporation
* JVM Vendor URL : http://java.oracle.com/

Maven配置如下：

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.0.4</version>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.53.Final</version>
        </dependency>

        <dependency>
            <groupId>org.fisco-bcos.java-sdk</groupId>
            <artifactId>fisco-bcos-java-sdk</artifactId>
            <version>2.9.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-log4j12</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.ethereum</groupId>
                    <artifactId>solcJ-all</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

java-sdk版本2.9.0、2.9.1都会报这个错误

**Comment by kyonRay** [comment]
看起来像是找不到证书，请确认一下证书是否在对应的目录下

**Comment by MJJ128** [comment]
> 看起来像是找不到证书，请确认一下证书是否在对应的目录下

移除MQ依赖后能正常启动，可以关注下 error info: PrivateKey type not supported PKCS#8 这个原因.

**Comment by kyonRay** [comment]
#206 检查一下是否与这个issue有关联？mq下也有netty依赖？
