### ISSUE TITLE
关于ssl handshake failed的问题

### ISSUE THREAD

**Issue by MaxSlion** [FISCO-BCOS/java-sdk#770]
按照官网的案例https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/sdk_application.html构建成功后，再x86-64的ubuntu上曾成功部署合约，java-sdk:2.9.1，随后我在aarch64设备上进行操作时，总是提示ssl handshake failed:/127.0.0.1:20200，sdk文件确保是完整nodes目录下的。
![1682183582666](https://user-images.githubusercontent.com/33566015/233797746-a7146fee-3853-45b3-b241-c36fa9010718.png)
这是aarch64设备报错内容，随后按照排查步骤检查了grep -iE 'SSLHandshakeException' sdk.log输出如下：
![1682183332603](https://user-images.githubusercontent.com/33566015/233797796-35d23a16-db3f-4a5c-b4a0-e5b75d77ad3e.png)
不太明白具体问题，尝试cat sdk.log|grep -E 'NoSuchMethodError|netty'后输出如下：
![1682183346916](https://user-images.githubusercontent.com/33566015/233797822-18085da5-5476-4d70-a5bc-49b36e572d5d.png)
修改了netty版本为4.1.53再次运行报错如下：
![1682183306130](https://user-images.githubusercontent.com/33566015/233797853-cefa3e34-1109-498b-a2c3-21b48dd01b06.png)
今天在x86-64设备上也报错证书错误，请问如何解决该问题

**Comment by MaxSlion** [comment]
重新安装的时候在控制台中调用HelloWorld会出现如下回执
![image](https://user-images.githubusercontent.com/33566015/233797991-c620497c-19ad-44ad-b88b-b9b8689ca737.png)
全新安装应该不存在上一个账户的情况，不知道是否和上述问题有关

**Comment by kyonRay** [comment]
会不会是使用了错误的证书，请确认一下证书是否正确。

**Comment by kyonRay** [comment]
> 重新安装的时候在控制台中调用HelloWorld会出现如下回执 ![image](https://user-images.githubusercontent.com/33566015/233797991-c620497c-19ad-44ad-b88b-b9b8689ca737.png) 全新安装应该不存在上一个账户的情况，不知道是否和上述问题有关

控制台如果不指定账号启动，那么第一次启动会默认生成一个账号到本地。

**Comment by MaxSlion** [comment]
是nodes文件夹下复制的，而且重新部署链后也报错这个问题…> 会不会是使用了错误的证书，请确认一下证书是否正确。

**Comment by MaxSlion** [comment]
> > 重新安装的时候在控制台中调用HelloWorld会出现如下回执 ![image](https://user-images.githubusercontent.com/33566015/233797991-c620497c-19ad-44ad-b88b-b9b8689ca737.png) 全新安装应该不存在上一个账户的情况，不知道是否和上述问题有关
> 
> 控制台如果不指定账号启动，那么第一次启动会默认生成一个账号到本地。

明白了 谢谢

**Comment by kyonRay** [comment]
> 是nodes文件夹下复制的，而且重新部署链后也报错这个问题…> 会不会是使用了错误的证书，请确认一下证书是否正确。

jdk是什么版本的？

**Comment by MaxSlion** [comment]
> > 是nodes文件夹下复制的，而且重新部署链后也报错这个问题…> 会不会是使用了错误的证书，请确认一下证书是否正确。
> 
> jdk是什么版本的？

x86-64上是openjdk version "11.0.18" 2023-01-17 看到最后输出是支持secp256k1
arm上尝试过jdk1.8.0_341与java version "11.0.16.1" 2022-08-18 LTS，输出上也是支持secp256k1

**Comment by MaxSlion** [comment]
当前环境：

**Comment by MaxSlion** [comment]
当前环境：
* FISCO BCOS Java SDK Version: 2.9.1
* Support secp256k1 : true
* Java Version : 11.0.2
* JDK Disabled NamedCurves : null
* JDK DisableNative Option : false
* OS Name : Linux
* OS Arch : amd64
* OS Version : 5.19.0-38-generic
* JVM Version : 11.0.2+9-LTS
修改console/start.sh为：
![9da83e93cb6dddb1bda36a5919cdef0](https://user-images.githubusercontent.com/33566015/233836276-4be2c96e-992d-4b36-b8cd-8d98cf299d40.png)
后启动console报错如下：
![9eba1ecc9bde9e69d7c1c5a0f26f2dc](https://user-images.githubusercontent.com/33566015/233836292-da98d565-f956-4590-a4f4-5abefea87f4b.png)
其中修改的是取消注释java -Djava.library.ffipath并将java -Djdk.tls.namedGroups置于其下一行。
在STEP1-1: Load certificates for ecdsa context success...看到其实证书已正确加载，不确定是否是复制过程的问题，我将console/conf/config.toml中的certPath指向了证书源目录：
![3af3ed76882b49c3434f987bf936e03](https://user-images.githubusercontent.com/33566015/233836487-9fd2ad22-e829-4a03-9024-0e4127ee2972.png)
![775decacb6173c113373d09286fc752](https://user-images.githubusercontent.com/33566015/233836497-fcf10862-8ee8-4755-992e-edcf24c80689.png)
问题依旧存在

**Comment by MaxSlion** [comment]
问题已解决，使用了非国联部署，并在本地进行连接部署合约操作，非远端配置
![image](https://user-images.githubusercontent.com/33566015/233899401-54e94683-5885-43b0-a2cd-e87ff70faed3.png)
